name: njsscan
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'